"""add credits to user

Revision ID: d81af2998be3
Revises: 62fc31f121cc
Create Date: 2026-04-04 19:02:55.203158

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d81af2998be3"
down_revision: str | Sequence[str] | None = "62fc31f121cc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("credits", sa.Integer(), server_default="100", nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "credits")
    # ### end Alembic commands ###
