"""
Domain prompt optimizer — Prompt Duel Optimizer (PDO).

Implements the Double Thompson Sampling algorithm from arXiv:2510.13907
("Dueling Optimization with a Monotone Adversary") as applied in
meta-llama/prompt-ops.

Pipeline:
  1. Generate K candidate prompt variants from the base prompt.
  2. Run T tournament rounds using Double Thompson Sampling (D-TS):
       - Sample theta_ij ~ Beta(W[i,j]+1, W[j,i]+1) for each candidate pair.
       - Select the pair (i*, j*) with the highest sampled win probability.
       - Duel: run both prompts on a randomly drawn Q&A pair; LLM judge picks winner.
       - Update W and N matrices.
  3. After every M rounds, generate a new mutation of the current best candidate
     and add it to the pool (top-performer guided mutation).
  4. Rank candidates using 5 systems:
       Copeland, Borda, Average Win Rate, Elo, TrueSkill
  5. Fuse rankings via Dirichlet-weighted ensemble (w ~ Dir(1^5)).
  6. Return the fused winner.

Constants are tuned for interactive web use (fewer rounds than the full paper):
  - K=5 initial candidates
  - T=40 tournament rounds
  - M=10 mutation interval
"""

from __future__ import annotations

import json
import logging
import math
import random
import textwrap
from dataclasses import dataclass, field
from typing import Any

from langchain_openai import ChatOpenAI

_log = logging.getLogger(__name__)

# ── Tuning constants ──────────────────────────────────────────────────────────
_NUM_CANDIDATES = 5  # initial prompt variants
_TOURNAMENT_ROUNDS = 40  # D-TS duel iterations (paper uses 100+; 40 balances speed/quality)
_MUTATION_INTERVAL = 10  # regenerate a new mutation every N rounds
_UCB_ALPHA = 0.5  # confidence-bound exploration weight (paper §4.1)
_ELO_K = 32.0  # Elo K-factor
_MAX_VAL_EXAMPLES = 20  # cap validation set used for final scoring
_MAX_SCORE_EXAMPLES = 8  # cap per-prompt eval examples during tournament

# ── LLM system prompts ────────────────────────────────────────────────────────
_VARIANT_SYSTEM = textwrap.dedent("""
    You are a prompt engineering expert.
    Given a base system prompt for a specific domain, generate {n} improved variants.
    Each variant should:
    - Preserve the original intent and domain focus
    - Be clearer, more specific, and better structured
    - Include explicit output format instructions if appropriate
    - Be suitable as a system prompt for an AI assistant

    Output ONLY a JSON array of strings, each string being one complete variant.
    No preamble, no explanation, no markdown fences.
""").strip()

_MUTATION_SYSTEM = textwrap.dedent("""
    You are a prompt engineering expert.
    Given a high-performing system prompt, produce one improved mutation.
    The mutation should:
    - Keep the core intent and domain focus intact
    - Vary the structure, framing, or specificity in a meaningful way
    - Not be identical to the original

    Output ONLY the mutated prompt text. No preamble, no explanation.
""").strip()

_DUEL_SYSTEM = textwrap.dedent("""
    You are an impartial evaluation judge.
    You will be shown a question, its gold-standard answer, and two responses
    generated by different system prompts (Prompt A and Prompt B).

    Choose which response better answers the question relative to the gold answer.

    Output ONLY a JSON object: {"winner": "A"} or {"winner": "B"}
    No explanation. No other keys.
""").strip()

_SCORE_SYSTEM = textwrap.dedent("""
    You are an evaluation judge.
    Given a question, a gold answer, and a model's answer, rate how well
    the model's answer matches the gold answer on a scale from 0.0 to 1.0.

    0.0 = completely wrong or irrelevant
    0.5 = partially correct
    1.0 = fully correct and equivalent to gold answer

    Output ONLY a JSON object: {"score": <float>}
    No explanation.
""").strip()


# ── Data structures ───────────────────────────────────────────────────────────
@dataclass
class _Candidate:
    text: str
    elo: float = 1200.0


@dataclass
class _WinMatrix:
    """Pairwise win (W) and comparison-count (N) matrices."""

    size: int
    W: list[list[float]] = field(default_factory=list)
    N: list[list[float]] = field(default_factory=list)

    def __post_init__(self) -> None:
        self.W = [[0.0] * self.size for _ in range(self.size)]
        self.N = [[0.0] * self.size for _ in range(self.size)]

    def add_candidate(self) -> None:
        n = self.size
        for row in self.W:
            row.append(0.0)
        for row in self.N:
            row.append(0.0)
        self.W.append([0.0] * (n + 1))
        self.N.append([0.0] * (n + 1))
        self.size += 1

    def record_win(self, winner: int, loser: int) -> None:
        self.W[winner][loser] += 1.0
        self.N[winner][loser] += 1.0
        self.N[loser][winner] += 1.0


# ── LLM helpers ───────────────────────────────────────────────────────────────
def _strip_fences(text: str) -> str:
    if text.startswith("```"):
        parts = text.split("```")
        text = parts[1] if len(parts) > 1 else text
        if text.startswith("json"):
            text = text[4:]
    return text.strip()


async def _generate_variants(base_prompt: str, n: int, llm: ChatOpenAI) -> list[str]:
    try:
        response = await llm.ainvoke(
            [
                {"role": "system", "content": _VARIANT_SYSTEM.format(n=n)},
                {"role": "user", "content": f"Base prompt:\n\n{base_prompt}"},
            ]
        )
        raw = _strip_fences(str(response.content).strip())
        variants: Any = json.loads(raw)
        if isinstance(variants, list) and all(isinstance(v, str) for v in variants):
            return [v for v in variants[:n] if v.strip()]
    except Exception as exc:  # noqa: BLE001
        _log.warning("Variant generation failed: %s", exc)
    return [base_prompt]


async def _mutate_prompt(prompt: str, llm: ChatOpenAI) -> str:
    try:
        response = await llm.ainvoke(
            [
                {"role": "system", "content": _MUTATION_SYSTEM},
                {"role": "user", "content": f"Prompt to mutate:\n\n{prompt}"},
            ]
        )
        mutated = str(response.content).strip()
        if mutated:
            return mutated
    except Exception as exc:  # noqa: BLE001
        _log.warning("Mutation failed: %s", exc)
    return prompt


async def _get_answer(prompt: str, question: str, llm: ChatOpenAI) -> str:
    try:
        response = await llm.ainvoke(
            [
                {"role": "system", "content": prompt},
                {"role": "user", "content": question},
            ]
        )
        return str(response.content).strip()
    except Exception as exc:  # noqa: BLE001
        _log.warning("Inference failed: %s", exc)
        return ""


async def _duel(
    prompt_a: str,
    prompt_b: str,
    question: str,
    gold: str,
    llm: ChatOpenAI,
    judge_llm: ChatOpenAI,
) -> int:
    """Return 0 if A wins, 1 if B wins."""
    ans_a, ans_b = (
        await _get_answer(prompt_a, question, llm),
        await _get_answer(prompt_b, question, llm),
    )
    try:
        response = await judge_llm.ainvoke(
            [
                {"role": "system", "content": _DUEL_SYSTEM},
                {
                    "role": "user",
                    "content": (
                        f"Question: {question}\n"
                        f"Gold answer: {gold}\n\n"
                        f"Response A:\n{ans_a}\n\n"
                        f"Response B:\n{ans_b}"
                    ),
                },
            ]
        )
        raw = _strip_fences(str(response.content).strip())
        result: Any = json.loads(raw)
        winner = str(result.get("winner", "A")).upper()
        return 0 if winner == "A" else 1
    except Exception as exc:  # noqa: BLE001
        _log.warning("Duel judge failed: %s", exc)
        return 0


async def _score_prompt(
    prompt: str,
    examples: list[dict[str, str]],
    llm: ChatOpenAI,
    judge_llm: ChatOpenAI,
) -> float:
    if not examples:
        return 0.0
    scores: list[float] = []
    for ex in examples[:_MAX_SCORE_EXAMPLES]:
        question = ex["question"]
        gold = ex["answer"]
        predicted = await _get_answer(prompt, question, llm)
        try:
            response = await judge_llm.ainvoke(
                [
                    {"role": "system", "content": _SCORE_SYSTEM},
                    {
                        "role": "user",
                        "content": (
                            f"Question: {question}\nGold answer: {gold}\n"
                            f"Model answer: {predicted}"
                        ),
                    },
                ]
            )
            raw = _strip_fences(str(response.content).strip())
            obj: Any = json.loads(raw)
            s = float(obj.get("score", 0.0))
            scores.append(max(0.0, min(1.0, s)))
        except Exception as exc:  # noqa: BLE001
            _log.warning("Score judge failed: %s", exc)
            scores.append(0.0)
    return sum(scores) / len(scores) if scores else 0.0


# ── PDO ranking systems ───────────────────────────────────────────────────────
def _copeland_scores(wm: _WinMatrix) -> list[float]:
    """Net wins: number of opponents candidate i beats majority of duels against."""
    n = wm.size
    scores = [0.0] * n
    for i in range(n):
        for j in range(n):
            if i == j:
                continue
            # Optimistic UCB estimate for p_ij
            n_ij = wm.N[i][j]
            if n_ij == 0:
                p_ij = 1.0  # optimistic: assume wins all unseen matchups
            else:
                p_ij = wm.W[i][j] / n_ij + math.sqrt(_UCB_ALPHA * math.log(max(n_ij, 1)) / n_ij)
                p_ij = min(p_ij, 1.0)
            if p_ij > 0.5:
                scores[i] += 1.0
    return scores


def _borda_scores(wm: _WinMatrix) -> list[float]:
    """Average fractional wins against each opponent."""
    n = wm.size
    scores = [0.0] * n
    for i in range(n):
        total = 0.0
        for j in range(n):
            if i == j:
                continue
            n_ij = wm.N[i][j]
            total += (wm.W[i][j] / n_ij) if n_ij > 0 else 0.5
        scores[i] = total / (n - 1) if n > 1 else 0.0
    return scores


def _avg_win_rate_scores(wm: _WinMatrix) -> list[float]:
    n = wm.size
    scores = [0.0] * n
    for i in range(n):
        wins = sum(wm.W[i][j] for j in range(n) if j != i)
        total = sum(wm.N[i][j] for j in range(n) if j != i)
        scores[i] = wins / total if total > 0 else 0.5
    return scores


def _elo_scores(candidates: list[_Candidate]) -> list[float]:
    return [c.elo for c in candidates]


def _trueskill_scores(wm: _WinMatrix) -> list[float]:
    """Simplified TrueSkill: Gaussian mean estimate from win rate with uncertainty."""
    n = wm.size
    scores = [0.0] * n
    for i in range(n):
        total = sum(wm.N[i][j] for j in range(n) if j != i)
        wins = sum(wm.W[i][j] for j in range(n) if j != i)
        mu = wins / total if total > 0 else 0.5
        # Shrink toward prior 0.5 proportional to uncertainty (Bayesian estimate)
        confidence = total / (total + 10)
        scores[i] = confidence * mu + (1 - confidence) * 0.5
    return scores


def _rank_from_scores(scores: list[float]) -> list[int]:
    """Return rank positions (0 = best) for each candidate by descending score."""
    indexed = sorted(enumerate(scores), key=lambda x: x[1], reverse=True)
    ranks = [0] * len(scores)
    for rank, (idx, _) in enumerate(indexed):
        ranks[idx] = rank
    return ranks


def _dirichlet_sample(n: int, rng: random.Random) -> list[float]:
    """Sample w ~ Dirichlet(1^n) via Gamma(1,1) trick."""
    gammas = [-math.log(rng.random() + 1e-15) for _ in range(n)]
    total = sum(gammas)
    return [g / total for g in gammas]


def _fuse_rankings(
    wm: _WinMatrix,
    candidates: list[_Candidate],
    rng: random.Random,
) -> int:
    """
    Multi-Ranker Fusion with Dirichlet-weighted ensemble (paper §5).

    Five ranking systems contribute rank positions for each candidate.
    Weights w ~ Dir(1^5) are sampled fresh each call so the fusion is
    stochastic and avoids deterministic ties.

    Returns the index of the fused winner.
    """
    rank_systems = [
        _rank_from_scores(_copeland_scores(wm)),
        _rank_from_scores(_borda_scores(wm)),
        _rank_from_scores(_avg_win_rate_scores(wm)),
        _rank_from_scores(_elo_scores(candidates)),
        _rank_from_scores(_trueskill_scores(wm)),
    ]
    weights = _dirichlet_sample(len(rank_systems), rng)
    n = wm.size

    # Weighted rank sum (lower = better)
    fused = [
        sum(weights[k] * rank_systems[k][i] for k in range(len(rank_systems))) for i in range(n)
    ]
    return int(min(range(n), key=lambda i: fused[i]))


# ── D-TS pair selection ───────────────────────────────────────────────────────
def _select_duel_pair(wm: _WinMatrix, rng: random.Random) -> tuple[int, int]:
    """
    Double Thompson Sampling (D-TS) — paper Algorithm 1.

    For each pair (i, j), sample theta_ij ~ Beta(W[i,j]+1, W[j,i]+1).
    Select the pair with the highest theta.
    Returns (champion, challenger).
    """
    n = wm.size
    best_theta = -1.0
    best_i, best_j = 0, 1

    for i in range(n):
        for j in range(n):
            if i == j:
                continue
            alpha = wm.W[i][j] + 1.0
            beta = wm.W[j][i] + 1.0
            # Sample from Beta(alpha, beta) via Gamma ratio
            g_a = -(math.log(rng.random() + 1e-15) ** (1.0 / alpha)) if alpha > 0 else 1e-6
            g_b = -(math.log(rng.random() + 1e-15) ** (1.0 / beta)) if beta > 0 else 1e-6
            theta = g_a / (g_a + g_b + 1e-15)
            if theta > best_theta:
                best_theta = theta
                best_i, best_j = i, j

    return best_i, best_j


def _update_elo(candidates: list[_Candidate], winner: int, loser: int) -> None:
    ea = 1.0 / (1.0 + 10 ** ((candidates[loser].elo - candidates[winner].elo) / 400.0))
    candidates[winner].elo += _ELO_K * (1.0 - ea)
    candidates[loser].elo -= _ELO_K * (1.0 - ea)


# ── Main entry point ──────────────────────────────────────────────────────────
async def optimize_domain_prompt(
    base_prompt: str,
    dataset_jsonl: str,
    api_key: str,
    num_candidates: int = _NUM_CANDIDATES,
) -> dict[str, object]:
    """
    Run the PDO algorithm and return the best domain-specific system prompt.

    Returns dict with keys:
        optimized_prompt (str)
        score_before     (float, 0–1)
        score_after      (float, 0–1)
    """
    # ── Parse dataset ─────────────────────────────────────────────────────────
    pairs: list[dict[str, str]] = []
    for line in dataset_jsonl.strip().splitlines():
        try:
            pairs.append(json.loads(line))
        except Exception as exc:  # noqa: BLE001
            _log.warning("JSONL parse failed: %s", exc)

    if not pairs:
        return {"optimized_prompt": base_prompt, "score_before": 0.0, "score_after": 0.0}

    # 70/15/15 split — consistent seed so reruns are reproducible
    rng = random.Random(42)  # noqa: S311
    shuffled = list(pairs)
    rng.shuffle(shuffled)
    n_total = len(shuffled)
    n_val = max(1, int(n_total * 0.15))
    val_split = shuffled[-n_val:]
    duel_pool = shuffled[: n_total - n_val]  # used during tournament duels

    if not duel_pool:
        duel_pool = shuffled  # tiny dataset fallback

    # ── LLM clients ───────────────────────────────────────────────────────────
    fast_llm = ChatOpenAI(
        model="openai/gpt-4o-mini",
        openai_api_base="https://openrouter.ai/api/v1",
        openai_api_key=api_key,
        temperature=0.7,
        max_tokens=512,
    )
    judge_llm = ChatOpenAI(
        model="openai/gpt-4o-mini",
        openai_api_base="https://openrouter.ai/api/v1",
        openai_api_key=api_key,
        temperature=0.0,
        max_tokens=64,
    )

    # ── Baseline score ────────────────────────────────────────────────────────
    score_before = await _score_prompt(
        base_prompt, val_split[:_MAX_VAL_EXAMPLES], fast_llm, judge_llm
    )

    # ── Generate initial candidates ───────────────────────────────────────────
    variant_texts = await _generate_variants(base_prompt, num_candidates, fast_llm)
    if base_prompt not in variant_texts:
        variant_texts.insert(0, base_prompt)  # always duel against baseline
    variant_texts = variant_texts[:num_candidates]

    candidates = [_Candidate(text=t) for t in variant_texts]
    wm = _WinMatrix(size=len(candidates))

    # ── PDO tournament (Double Thompson Sampling) ─────────────────────────────
    for round_idx in range(_TOURNAMENT_ROUNDS):
        i, j = _select_duel_pair(wm, rng)
        ex = rng.choice(duel_pool)
        question, gold = ex["question"], ex["answer"]

        # _duel returns 0 (i wins) or 1 (j wins)
        duel_result = await _duel(
            candidates[i].text, candidates[j].text, question, gold, fast_llm, judge_llm
        )
        winner_idx, loser_idx = (i, j) if duel_result == 0 else (j, i)
        wm.record_win(winner_idx, loser_idx)
        _update_elo(candidates, winner_idx, loser_idx)

        # Top-performer guided mutation every M rounds
        if (round_idx + 1) % _MUTATION_INTERVAL == 0:
            best_now = _fuse_rankings(wm, candidates, rng)
            mutated_text = await _mutate_prompt(candidates[best_now].text, fast_llm)
            if mutated_text not in {c.text for c in candidates}:
                candidates.append(_Candidate(text=mutated_text, elo=candidates[best_now].elo))
                wm.add_candidate()
                _log.info("Round %d: added mutation (pool size=%d)", round_idx + 1, wm.size)

    # ── Multi-Ranker Fusion to find overall winner ────────────────────────────
    winner_idx = _fuse_rankings(wm, candidates, rng)
    best_prompt = candidates[winner_idx].text

    # ── Final score on held-out val split ─────────────────────────────────────
    score_after = await _score_prompt(
        best_prompt, val_split[:_MAX_VAL_EXAMPLES], fast_llm, judge_llm
    )

    _log.info(
        "PDO complete: %d candidates, %d rounds, score %.3f → %.3f",
        len(candidates),
        _TOURNAMENT_ROUNDS,
        score_before,
        score_after,
    )

    return {
        "optimized_prompt": best_prompt,
        "score_before": round(score_before, 4),
        "score_after": round(score_after, 4),
    }
